-- =============================================================================
-- SP_CASCADE_SUMMARY  |  Credit Campaign Analytics Dashboard
-- =============================================================================
-- Purpose : Orchestrates the full filter cascade pipeline for a given period,
--           populating the BD_CASCADAS_FINALES table consumed by the Power BI
--           Cascada tab.
--
-- Architecture (2-stage execution):
--   Stage 1 (@ETAPA=1):
--     - Copies MAESTRO_FILTROS from previous period
--     - Runs SP_CASCADAS_FILTROS_KILLER and SP_CASCADAS_FILTROS_DUROS
--     - Runs 12+ campaign-specific cascade sub-procedures:
--       APROBADOS : EAI, RECURRENTE, PILOTO1-4, REENGANCHE, PILOTO8-9, NUEVOS
--       EVALUABLES: EAI, BLINDAJE, ATAQUE
--
--   Stage 2 (@ETAPA=2):
--     - Consolidates all cascade outputs into BD_CASCADAS_FINALES
--     - Runs after the offer table (OfertaCamp) is refreshed by business team
--
-- Usage:
--   EXEC dbo.SP_CASCADE_SUMMARY '202601', 1   -- after master filter update
--   EXEC dbo.SP_CASCADE_SUMMARY '202601', 2   -- after offer table refresh
-- =============================================================================

/****** Object:  StoredProcedure [dbo].[SP_CASCADAS_RESUMEN]    Script Date: 13/02/2026 09:51:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--exec [dbo].[SP_CASCADAS_RESUMEN] '202601',2
ALTER PROC [dbo].[SP_CASCADAS_RESUMEN] (@PERIODO VARCHAR(6),@ETAPA INT) AS

BEGIN
	DECLARE
		@MAX_PERIODO DATE;

	IF @ETAPA = 1 

	BEGIN
		-- HACEMOS COPIA DE LA TABLA DE FILTROS (SI HAY CAMBIOS MODIFICAR MANUALMENTE O CARGAR EXCEL)
		DELETE FROM MAESTRO_FILTROS
		WHERE PERIODO = @PERIODO

		INSERT INTO MAESTRO_FILTROS
		SELECT @PERIODO,ORDEN_TIPO_FILTRO,TIPO_FILTRO,ORDEN_TIPO_CAMPAÑA,	TIPO_CAMPAÑA,	ORDEN_CAMPAÑA,	CAMPAÑA,	ORDEN_FILTRO,	FILTRO,	NOMBRE,	VIGENCIA
		FROM MAESTRO_FILTROS
		WHERE PERIODO = CONVERT(VARCHAR(6),DATEADD(MONTH,-1,CAST(@PERIODO+'01' AS DATE)),112)
		
		EXEC DBO.SP_CASCADAS_FILTROS_KILLER				   @PERIODO
		EXEC DBO.SP_CASCADAS_FILTROS_DUROS				   @PERIODO

		---APROBADOS
		EXEC [dbo].[SP_CASCADAS_APROBADOS_EAI]			   @PERIODO
		EXEC [dbo].[SP_CASCADAS_APROBADOS_RECURRENTE]	   @PERIODO
		EXEC [dbo].[SP_CASCADAS_APROBADOS_PILOTO1]		   @PERIODO
		EXEC [dbo].[SP_CASCADAS_APROBADOS_PILOTO2]		   @PERIODO
		EXEC [dbo].[SP_CASCADAS_APROBADOS_PILOTO3]		   @PERIODO
		EXEC [dbo].[SP_CASCADAS_APROBADOS_PILOTO4]		   @PERIODO
		EXEC [dbo].[SP_CASCADAS_APROBADOS_REENGANCHE]	   @PERIODO
		EXEC [dbo].[SP_CASCADAS_APROBADOS_PILOTO8]		   @PERIODO
		EXEC [dbo].[SP_CASCADAS_APROBADOS_PILOTO9]		   @PERIODO
		
		EXEC [dbo].[SP_CASCADAS_APROBADOS_NUEVOS]		   @PERIODO

	
		if object_id('DBO.TEMP_BASE_APROBADOS_EAI') is not null drop table DBO.TEMP_BASE_APROBADOS_EAI
		if object_id('DBO.TEMP_BASE_APROBADOS_RECURRENTE') is not null drop table DBO.TEMP_BASE_APROBADOS_RECURRENTE
		if object_id('DBO.TEMP_BASE_APROBADOS_PILOTO1') is not null drop table DBO.TEMP_BASE_APROBADOS_PILOTO1
		if object_id('DBO.TEMP_BASE_APROBADOS_PILOTO2') is not null drop table DBO.TEMP_BASE_APROBADOS_PILOTO2
		if object_id('DBO.TEMP_BASE_APROBADOS_PILOTO3') is not null drop table DBO.TEMP_BASE_APROBADOS_PILOTO3
		if object_id('DBO.TEMP_BASE_APROBADOS_PILOTO4') is not null drop table DBO.TEMP_BASE_APROBADOS_PILOTO4
		if object_id('DBO.TEMP_BASE_APROBADOS_REENGANCHE') is not null drop table	DBO.TEMP_BASE_APROBADOS_REENGANCHE
		if object_id('DBO.TEMP_BASE_APROBADOS_PILOTO8') is not null drop table		DBO.TEMP_BASE_APROBADOS_PILOTO8
		if object_id('DBO.TEMP_BASE_APROBADOS_PILOTO9') is not null drop table		DBO.TEMP_BASE_APROBADOS_PILOTO9
	
	
		--EVALUABLES
		EXEC [dbo].[SP_CASCADAS_EVALUABLES_EAI]			   @PERIODO
		EXEC [dbo].[SP_CASCADAS_EVALUABLES_BLINDAJE]	   @PERIODO
		EXEC [dbo].[SP_CASCADAS_EVALUABLES_ATAQUE]		   @PERIODO

		if object_id('DBO.TEMP_BASE_EVALUABLES_EAI') is not null drop table			DBO.TEMP_BASE_EVALUABLES_EAI
		if object_id('DBO.TEMP_BASE_EVALUABLES_BLINDAJE') is not null drop table	DBO.TEMP_BASE_EVALUABLES_BLINDAJE
		if object_id('DBO.TEMP_BASE_EVALUABLES_ATAQUE') is not null drop table		DBO.TEMP_BASE_EVALUABLES_ATAQUE
	
	END

	IF @ETAPA = 2

	BEGIN
		--TABLA ORDENADA
		DROP TABLE HAR_CASCADA_RESUMEN_ORDENADO

		SELECT 
		CAST(A.PERIODO + '01' AS DATE) COD_MES,
		A.PERIODO,
		B.ORDEN_TIPO_CAMPAÑA,
		A.CONJUNTO,
		B.ORDEN_CAMPAÑA,
		A.CAMPAÑA,
		B.ORDEN_FILTRO,
		A.FILTRO,
		A.NOMBRE_FILTRO,
		A.PASAN,
		A.NoAplicaCount CAIDA_INDIVIDUAL,
		A.CaidaUnica CAIDA_UNICA,
		A.UNIVERSO
		INTO HAR_CASCADA_RESUMEN_ORDENADO
		FROM HAR_CASCADAS_RESUMEN a
		left join MAESTRO_FILTROS B
		ON A.PERIODO=B.PERIODO AND A.CAMPAÑA=CASE WHEN B.CAMPAÑA = '' THEN B.TIPO_FILTRO ELSE B.CAMPAÑA END AND A.FILTRO=B.FILTRO AND A.CONJUNTO = B.TIPO_CAMPAÑA
		ORDER BY 1,3,5

		--SELECT * FROM MAESTRO_FILTROS

		-- TABLA CON METRICAS
		DELETE FROM HAR_CASCADA_RESUMEN_ORDENADO_CONSOLIDADO
		WHERE PERIODO = @PERIODO

		INSERT INTO HAR_CASCADA_RESUMEN_ORDENADO_CONSOLIDADO
		SELECT 
			A.*,
			(case when a.ORDEN_FILTRO = 1 then a.universo - a.pasan else C.Pasan - a.Pasan end) CAIDA_CASCADA,
			(A.Pasan - B.Pasan) DIF_PASAN,
			(A.CAIDA_INDIVIDUAL - B.CAIDA_INDIVIDUAL) DIF_CAIDA_INDIVIDUAL,
			(A.CAIDA_UNICA - B.CAIDA_UNICA) DIF_CAIDA_UNICA,
			CASE WHEN A.UNIVERSO = 0 THEN NULL ELSE A.CAIDA_INDIVIDUAL/(A.UNIVERSO*1.0) END PROPORCION_CI_MACT,
			CASE WHEN B.UNIVERSO = 0 THEN NULL ELSE B.CAIDA_INDIVIDUAL/(B.UNIVERSO*1.0) END PROPORCION_CI_MANT,
			CASE WHEN A.UNIVERSO = 0 THEN NULL ELSE A.CAIDA_UNICA/(A.UNIVERSO*1.0) END PROPORCION_CU_MACT,
			CASE WHEN B.UNIVERSO = 0 THEN NULL ELSE B.CAIDA_UNICA/(B.UNIVERSO*1.0) END PROPORCION_CU_MANT,
			(CASE WHEN A.UNIVERSO = 0 THEN NULL ELSE A.CAIDA_INDIVIDUAL/(A.UNIVERSO*1.0) END - CASE WHEN B.UNIVERSO =0 THEN NULL ELSE B.CAIDA_INDIVIDUAL/(B.UNIVERSO*1.0) END) DIF_PROPORCION_CI,
			(CASE WHEN A.UNIVERSO = 0 THEN NULL ELSE A.CAIDA_UNICA/(A.UNIVERSO*1.0) END - CASE WHEN B.UNIVERSO =0 THEN NULL ELSE B.CAIDA_UNICA/(B.UNIVERSO*1.0) END) DIF_PROPORCION_CU

		FROM (SELECT * FROM HAR_CASCADA_RESUMEN_ORDENADO WHERE PERIODO = @PERIODO) A
		LEFT JOIN (SELECT * FROM HAR_CASCADA_RESUMEN_ORDENADO WHERE PERIODO = CONVERT(VARCHAR(6),DATEADD(MONTH,-1,CAST(@PERIODO + '01' AS DATE)),112)) B
		ON A.ORDEN_TIPO_CAMPAÑA=B.ORDEN_TIPO_CAMPAÑA 
		AND A.ORDEN_CAMPAÑA = B.ORDEN_CAMPAÑA AND A.ORDEN_FILTRO = B.ORDEN_FILTRO AND A.CAMPAÑA = B.CAMPAÑA
		LEFT JOIN HAR_CASCADA_RESUMEN_ORDENADO C
		ON A.COD_MES = c.COD_MES AND A.ORDEN_TIPO_CAMPAÑA=C.ORDEN_TIPO_CAMPAÑA 
		AND A.ORDEN_CAMPAÑA = C.ORDEN_CAMPAÑA AND A.ORDEN_FILTRO = C.ORDEN_FILTRO + 1 AND A.CAMPAÑA = c.CAMPAÑA 
		--WHERE A.PERIODO = @PERIODO_MIN
		union all
		SELECT 
			COD_MES,PERIODO,ORDEN_TIPO_CAMPAÑA,CONJUNTO,ORDEN_CAMPAÑA,CAMPAÑA,NULL,'F999' FILTRO,'Universo inicial' NOMBRE_FILTRO,
			MAX(UNIVERSO) PASAN,NULL,NULL,MAX(Universo) UNIVERSO,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
		FROM HAR_CASCADA_RESUMEN_ORDENADO A WHERE PERIODO = @PERIODO AND CONJUNTO IN ('APROBADOS','EVALUABLES','FILTROS DUROS') and Universo>0
		GROUP BY 
			COD_MES,PERIODO,ORDEN_TIPO_CAMPAÑA,CONJUNTO,ORDEN_CAMPAÑA,CAMPAÑA
		union all
		SELECT 
			A.dFechaOferta,A.PERIODO,b.ORDEN_TIPO_CAMPAÑA,b.TIPO_CAMPAÑA,b.ORDEN_CAMPAÑA,A.CAMPAÑA_FINAL,b.orden_filtro+1,'F000' FILTRO,'Otros (CEM, Score, etc.)' NOMBRE_FILTRO,
			sum(q) PASAN,NULL,NULL,sum(q) UNIVERSO,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
		FROM (SELECT *, CASE 
		WHEN TIPO_NOMBRE_CARGA = 'EAI' THEN 'EAI'
		WHEN TIPO_NOMBRE_CARGA = 'RECURRENTE' THEN 'RECURRENTE'
		WHEN TIPO_NOMBRE_CARGA = 'PILOTO 1: Capacidad de pago' THEN 'PILOTO1'
		WHEN TIPO_NOMBRE_CARGA = 'PILOTO 2: Avance de cuota' THEN 'PILOTO2'
		WHEN TIPO_NOMBRE_CARGA IN ('Piloto 3 – Rapicrédito - Recurrente Flexible','PILOTO 3: Recurente flexible') THEN 'PILOTO3'
		WHEN TIPO_NOMBRE_CARGA IN ('Piloto 4 – Rapicrédito - Atraso', 'PILOTO 4: Atraso') THEN 'PILOTO4'
		WHEN TIPO_NOMBRE_CARGA = 'REENGANCHE' THEN 'REENGANCHE'
		WHEN TIPO_NOMBRE_CARGA = 'NUEVOS' THEN 'NUEVOS'
		WHEN TIPO_NOMBRE_CARGA = 'BLINDAJE' THEN 'BLINDAJE'
		WHEN TIPO_NOMBRE_CARGA = 'ATAQUE' THEN 'ATAQUE'
		WHEN TIPO_NOMBRE_CARGA = 'PILOTO 8: Capacidad de pago' THEN 'PILOTO8'
		WHEN TIPO_NOMBRE_CARGA = 'PILOTO 9: Tope Oferta 20M' THEN 'PILOTO9'
		ELSE TIPO_NOMBRE_CARGA END CAMPAÑA_FINAL 
		--SELECT MAX(PERIODO)
		FROM HAR_LEADS_RESUMEN ) A 
		left join (select periodo,ORDEN_TIPO_CAMPAÑA,TIPO_CAMPAÑA,ORDEN_CAMPAÑA,CAMPAÑA, MAX(ORDEN_FILTRO) ORDEN_FILTRO from MAESTRO_FILTROS
					WHERE TIPO_CAMPAÑA IN ('APROBADOS','EVALUABLES')
					GROUP BY periodo,ORDEN_TIPO_CAMPAÑA,TIPO_CAMPAÑA,ORDEN_CAMPAÑA,CAMPAÑA) b
		on a.PERIODO= b.PERIODO and a.TIPO_CAMPAÑA=b.TIPO_CAMPAÑA  AND A.CAMPAÑA_FINAL=B.CAMPAÑA
		WHERE A.PERIODO = @PERIODO and isnull(a.Observacion,'Pasa') = 'Pasa'
		GROUP BY 
			A.dFechaOferta,A.PERIODO,B.ORDEN_TIPO_CAMPAÑA,b.TIPO_CAMPAÑA,B.ORDEN_CAMPAÑA,CAMPAÑA_FINAL,b.orden_filtro
	
		-- TABLA FINAL CONSOLIDADA
		DELETE FROM HAR_CASCADA_RESUMEN_ORDENADO_CONSOLIDADO_FINAL
		WHERE PERIODO_MOVIL = @PERIODO

		INSERT INTO HAR_CASCADA_RESUMEN_ORDENADO_CONSOLIDADO_FINAL
		SELECT 
			CAST(@PERIODO+'01' AS DATE) COD_MES_MOVIL,
			@PERIODO PERIODO_MOVIL,* 
		FROM HAR_CASCADA_RESUMEN_ORDENADO_CONSOLIDADO
		WHERE PERIODO = @PERIODO
		UNION ALL
		SELECT 
			DATEADD(MONTH,1,CAST(PERIODO + '01' AS DATE)) COD_MES_MOVIL,
			CONVERT(VARCHAR(6),DATEADD(MONTH,1,CAST(PERIODO + '01' AS DATE)),112) PERIODO_MOVIL,* 
		FROM HAR_CASCADA_RESUMEN_ORDENADO_CONSOLIDADO
		WHERE PERIODO = CONVERT(VARCHAR(6),DATEADD(MONTH,-1,CAST(@PERIODO + '01' AS DATE)),112)

		-- TABLA A MOSTRAR EN REPORTE
		
		drop table HAR_CASCADAS_REPORTE

		SET @MAX_PERIODO = (SELECT MAX(COD_MES_MOVIL) FROM HAR_CASCADA_RESUMEN_ORDENADO_CONSOLIDADO_FINAL)
		
		SELECT *
		INTO HAR_CASCADAS_REPORTE
		FROM (
			SELECT A.*, CASE WHEN B.PERIODO IS NOT NULL THEN 1 ELSE 0 END FLAG_PASAN,
			CASE WHEN A.NOMBRE_FILTRO = 'Otros (CEM, Score, etc.)' then 20 else 
			row_number()over(partition by a.cod_mes_movil,a.cod_mes,a.orden_tipo_campaña,a.orden_campaña order by pasan desc, orden_filtro asc) end index_periodo, 
			DATEDIFF(MONTH,COD_MES,@MAX_PERIODO) ORDEN_PERIODO_TABLA
			FROM HAR_CASCADA_RESUMEN_ORDENADO_CONSOLIDADO_FINAL A
			LEFT JOIN (	
			SELECT PERIODO,ORDEN_TIPO_CAMPAÑA,ORDEN_CAMPAÑA, MAX(ORDEN_FILTRO) ORDEN
			FROM MAESTRO_FILTROS
			GROUP BY PERIODO,ORDEN_TIPO_CAMPAÑA,ORDEN_CAMPAÑA) B
			ON A.PERIODO = B.PERIODO AND A.ORDEN_TIPO_CAMPAÑA = B.ORDEN_TIPO_CAMPAÑA
				AND A.ORDEN_CAMPAÑA = B.ORDEN_CAMPAÑA AND A.ORDEN_FILTRO = B.ORDEN) F
			--WHERE PERIODO = 202508 AND CAMPAÑA = 'EAI' AND CONJUNTO = 'APROBADOS' and FILTRO NOT IN ('F900','F901')
	END

END
/*
insert maestro_filtros
select 
'202511'PERIODO,	FILTRO,	NOMBRE,	TIPO_FILTRO,	TIPO_CAMPAÑA,	CAMPAÑA,	VIGENCIA
from maestro_filtros where PERIODO = 202510
*/
 /*
SELECT COD_MES,ORDEN_PERIODO FROM (
SELECT
	COD_MES_MOVIL,COD_MES, DATEDIFF(MONTH,COD_MES,CAST('20260201' AS DATE)) ORDEN_PERIODO
 FROM HAR_CASCADA_RESUMEN_ORDENADO_CONSOLIDADO_FINAL
 ) A
GROUP BY COD_MES,ORDEN_PERIODO
ORDER BY 1

SELECT * FROM HAR_CASCADAS_REPORTE
WHERE PERIODO_MOVIL = 202602
*/
